### ISSUE TITLE
Error when running show.py

### ISSUE THREAD

**Issue by pbz134** [defgsus/teletext-archive-2024#1]
Hello,
I am using Python 3.10 in a Conda env and I am getting the following error when running show.py:

Traceback (most recent call last):
  File "D:\PythonTests\teletext-archive-2024\show.py", line 370, in <module>
    main(**parse_args())
  File "D:\PythonTests\teletext-archive-2024\show.py", line 346, in main
    viewer = Viewer(scraper, page, sub_page)
  File "D:\PythonTests\teletext-archive-2024\show.py", line 68, in __init__
    self.set_scraper(scraper)
  File "D:\PythonTests\teletext-archive-2024\show.py", line 244, in set_scraper
    self.set_page(self.page, self.sub_page)
  File "D:\PythonTests\teletext-archive-2024\show.py", line 252, in set_page
    self.page, self.sub_page = self.tt.get_next_page(page, sub_page, 0)
  File "D:\PythonTests\teletext-archive-2024\src\teletext\teletext.py", line 100, in get_next_page
    return self.page_index[0]
IndexError: list index out of range

**Comment by defgsus** [comment]
Hi @pbz134 , thanks for letting me know.

The 3sat channel was empty and the code did not expect a completely empty channel. It will now display "Sorry, this channel is empty."

However, the reason it was empty is that they changed the location and format of the teletext website. It's now below the realm of ZDF https://teletext.zdf.de/ 

cheers!
